name: Cleanup

on:
  push:

jobs:

  cleanup:
    runs-on: ubuntu-latest
    steps:
    -
      if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
      uses: rokroskar/workflow-run-cleanup-action@v0.3.3
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
