name: New Release
on:
  workflow_dispatch:
    branches: ['master']
    inputs:
      force_release:
        required: true
        description: "force bump patch version"
        default: "false"

jobs:

  release:
    name: Container Image & Helm Chart
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    -
      name: go-semantic-release
      uses: go-semantic-release/action@v1.11.2
      id: version
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allow-initial-development-versions: true
        changelog-generator-opt: "emojis=true"
        force-bump-patch-version: ${{ github.event.inputs.force_release }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1.1.0
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0
    -
      name: Docker login
      uses: docker/login-action@v1.9.0
      with:
        username: deyaeddin
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: deyaeddin/cert-manager-webhook-hetzner
        tags: |
          type=raw,value=${{ steps.version.outputs.version }}
          type=raw,value=latest
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
  # --------------------------------------------------------------------------------
    -
      name: Install helm
      if: ${{ steps.version.outputs.version != '' }}
      uses: azure/setup-helm@v1
    -
      name: Package Helm Charts
      if: ${{ steps.version.outputs.version != '' }}
      env:
        HELM_REPO: docs/chart
        CHART_DIR: charts/cert-manager-webhook-hetzner/
      run: |
        helm package "${CHART_DIR}" -d "${HELM_REPO}" --version "${{ steps.version.outputs.version }}" --app-version "${{ steps.version.outputs.version }}"
    -
      name: Index Helm Charts
      if: ${{ steps.version.outputs.version != '' }}
      env:
        HELM_REPO: docs/chart
        HELM_REPO_URL: https://deyaeddin.github.io/cert-manager-webhook-hetzner/chart
      run: |
        helm repo index --url "${HELM_REPO_URL}" "${HELM_REPO}"
    -
      name: Push to GitHub Pages
      if: ${{ steps.version.outputs.version != '' }}
      env:
        HELM_REPO: docs/chart
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "${GITHUB_ACTOR}"
        git fetch
        cp charts/cert-manager-webhook-hetzner/README.md "${HELM_REPO}"
        git add "${HELM_REPO}"
        git commit -m "chore: add helm charts for current release"
        git push
