name: Release

on:
  push:
    branches: [main]

jobs:

  release:
    name: Container Image & Helm Chart
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2.3.4
    -
      name: go-semantic-release
      uses: go-semantic-release/action@1.11.2
      id: version
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allow-initial-development-versions: true
        force-bump-patch-version: true
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1.1.0
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0
    -
      name: Docker login
      if: ${{ steps.version.outputs.version != '' }}
      uses: docker/login-action@v1.9.0
      with:
        username: deyaeddin
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Build release
      if: ${{ steps.version.outputs.version != '' }}
      run: make build IMAGE_TAG="${{ steps.version.outputs.version }}"
    -
      name: Push image release
      if: ${{ steps.version.outputs.version != '' }}
      run: make push-release IMAGE_TAG="${{ steps.version.outputs.version }}"
    -
      name: Build Edge
      run: make build-edge
    -
      name: Push Edge
      run: make push-edge
  # --------------------------------------------------------------------------------
    -
      name: Install helm
      if: ${{ steps.version.outputs.version != '' }}
      uses: azure/setup-helm@v1
    -
      name: Checkout branch for Chart repo
      if: ${{ steps.version.outputs.version != '' }}
      env:
        STATIC_BRANCH: helmrepo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "${GITHUB_ACTOR}"
        git fetch
        git checkout "${STATIC_BRANCH}"
    -
      name: Package Helm Charts
      if: ${{ steps.version.outputs.version != '' }}
      env:
        HELM_REPO: .
        CHART_DIR: chart/cert-manager-webhook-hetzner/
      run: |
        helm package "${CHART_DIR}" -d "${HELM_REPO}" --version "${{ steps.version.outputs.version }}"
    -
      name: Index Helm Charts
      if: ${{ steps.version.outputs.version != '' }}
      env:
        HELM_REPO: .
      run: |
        helm repo index --url "${HELM_REPO_URL}" "${HELM_REPO}"
    -
      name: Push to GitHub Pages
      if: ${{ steps.version.outputs.version != '' }}
      env:
        STATIC_BRANCH: helmrepo
        HELM_REPO: .
      run: |
        git add "${HELM_REPO}"
        git commit -m "chore: add helm charts for release ${{ steps.version.outputs.version }}"
        git push --set-upstream origin "${STATIC_BRANCH}"