name: Tests

on: [pull_request]

jobs:

  cert_manager_webhook_test:
    name: Cert-Manager Webhook Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.16.x ]
    steps:
       -
        name: checkout
        uses: actions/checkout@v2
       -
        name: run tests
        env:
          TEST_ZONE_NAME: ${{ secrets.TEST_ZONE_NAME }}
          HCLOUD_DNS_API_TOKEN: ${{ secrets.HCLOUD_DNS_API_TOKEN }}
        run: runing test


