name: Tests

on: [pull_request]

jobs:

  cert_manager_webhook_test:
    name: Cert-Manager Webhook Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.16.x ]
    steps:
       -
        name: checkout
        uses: actions/checkout@v2
       -
        name: get config.json secrets
        uses: jwsi/secret-parser@v1
        with:
          filename: testdata/hetzner/config.json
          secret-name: TEST_ZONE_NAME
          secret-value: ${{ secrets.TEST_ZONE_NAME }}
       -
        name: get hetzner secrets
        uses: jwsi/secret-parser@v1
        with:
          filename: testdata/hetzner/hetzner-secret.yml
          secret-name: HCLOUD_DNS_API_TOKEN
          secret-value: ${{ secrets.HCLOUD_DNS_API_TOKEN }}
       -
        name: run tests
        env:
          TEST_ZONE_NAME: ${{ secrets.TEST_ZONE_NAME }}
        run: make test


